### ISSUE TITLE
Unable to build with GCC 7.3

### ISSUE THREAD

**Issue by AJenbo** [bjornus/Radon#1]
https://github.com/bjornus/Radon/blob/9d2324393d3e2dd5f835938ff31d3b40fd07af86/Radon/source/File.cpp#L41

```
/home/ajenbo/code/devilutionX/3rdParty/Radon/Radon/source/File.cpp: In constructor ‘radon::File::File(const string&, bool)’:
/home/ajenbo/code/devilutionX/3rdParty/Radon/Radon/source/File.cpp:41:31: error: cannot bind non-const lvalue reference of type ‘radon::Key&’ to an rvalue of type ‘radon::Key’
       sections.back()->addKey(Key(nameOfElement, valueOfElement));
```

**Comment by AJenbo** [comment]
I got it working but encountered a few more issues:
- new keys not being saved
- crashes if key or section weren't pre existing 

I fixed the issues in this commit: https://github.com/diasurgical/devilutionX/commit/c2c0dd05f241c7a81874e243df0ecf091781bd6f
Tell me if you want me to send it as a PR, or if you prefer you can pick out the parts you agree with.

**Comment by AJenbo** [comment]
Fixed in https://github.com/szewczukk/Radon/pull/3
